name: Start a stopped ec2 instance, then copy over a docker compose file to be ran on the instance

on:
  push:   
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build: 

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: 3.137.182.108
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PASSWORD }}
        source: "docker-compose.yml"
        target: "/home/ubuntu/"